### ISSUE TITLE
duplicate print when using "v:" command

### ISSUE THREAD

**Issue by Rosyparadise** [Anas-Elgarhy/JConsoleAudioPlayer#10]
Linux Manjaro [Kernel 5.14.21-2-MANJARO]
Desktop KDE Plasma 5.23.5

The playlist and the menu are printed twice when volume is set after using "v:" command

1. run the program
2. type "v:"
3. input a number to set the volume 
4. playlist + menu is printed twice

**Comment by Rosyparadise** [comment]
It seems so. I'm working on it right now. I think if the Action is Unknown it shouldn't reprint the menu and the playlist. It seems to be working well that way. What do you think?

**Comment by Anas-Elgarhy** [comment]
And I think that this is appropriate because there is no change in the printed content
