### ISSUE TITLE
"exit" command works only if there are files in the cache 

### ISSUE THREAD

**Issue by Rosyparadise** [Anas-Elgarhy/JConsoleAudioPlayer#11]
Linux Manjaro [Kernel 5.14.21-2-MANJARO]
Desktop KDE Plasma 5.23.5

Trying to use the "exit" command when there are no saved files in the cache results in a Json Mapping Exception and the program terminates. Rerunning the program automatically throws more Json Mapping exceptions. 

1. start the program with an empty cache memory 
2. type "exit"
3. the program throws an error and is terminated
4. (optional) rerunning the program throws the error again with no action performed

After step 2:
![image](https://user-images.githubusercontent.com/68242418/153246032-beb6d83d-2bd4-4ee5-94f8-690e6768f39f.png)

**Comment by Anas-Elgarhy** [comment]
I'm thinking to make saving the last playlist separately from the rest of the settings because there may not be a playlist at all, unlike the rest of the settings that I save when I exit the program

**Comment by Anas-Elgarhy** [comment]
Fixed in https://github.com/Anas-Elgarhy/JConsoleAudioPlayer/commit/44a78be6eb2aef1d43f80fdcd524ebe8f96fcc7c
