### ISSUE TITLE
Files whose names end with wav but are not of .wav format.

### ISSUE THREAD

**Issue by Rosyparadise** [Anas-Elgarhy/JConsoleAudioPlayer#2]
Linux Manjaro [Kernel 5.14.21-2-MANJARO]
Desktop KDE Plasma 5.23.5

When the program is asked to search for .wav files to add to the playlist, it includes files whose name ends with wav but are not of .wav format. That leads to the player not being able to produce sound out of them and, therefore, throwing an unsupported audio file exception. 

1. Run the program
2. Type "open" to open the file browser
3.  Type "<"  to go from /home/[user_name] to /home
4. Type "<" again to go from /home to /
5. Type "+ 1" to add /usr to the list
6. Type "q" to return to the music player

At this point the bug become visible as the files don't have a .wav extension. Playing those files throws the exception 

I was expecting all the files available in the playlist after the search to be of .wav format. 

![image](https://user-images.githubusercontent.com/68242418/153055200-b0b2fefd-408b-47fc-aa24-4008137aea29.png)

![image](https://user-images.githubusercontent.com/68242418/153055356-5fc47292-3bbd-43de-be8b-ac6f093aa0d4.png)

**Comment by Anas-Elgarhy** [comment]
Oh, thanks I didn't think about this case and I'm setting file filtering rules, but I think we can solve this problem by making sure the filename ends with `.extension` instead of `extension`

**Comment by Anas-Elgarhy** [comment]
Or do you have a better solution?

**Comment by Rosyparadise** [comment]
i think that's ideal! :)

**Comment by Anas-Elgarhy** [comment]
Ok, fine
