### ISSUE TITLE
Exit only works after a song has been played 

### ISSUE THREAD

**Issue by Rosyparadise** [Anas-Elgarhy/JConsoleAudioPlayer#5]
Linux Manjaro [Kernel 5.14.21-2-MANJARO]
Desktop KDE Plasma 5.23.5

"exit" command only works after a song has played. Trying to exit the program by typing "exit" as the program starts, after using a command or after loading tracks to the playlist results to a null pointer exception error. "exit" command only works after using command "p" when there are tracks loaded in the playlist.

some error scenarios are:

1. start the program
2. type "exit"
3. error

and

1. start the program
2. type "open"
3. type "<"
4. type "+ 1" to load user's .wav files to playlist
5. type "q" to return to the player
6. type "exit"
7. error

scenario where "exit" works:

1. start the program
2. type "open"
3. type "<"
4. type "+ 1" to load user's .wav files to playlist
5. type "q" to return to the player
6.  type "p" to play a file
7. type "exit"
8. success

I expect to be able to exit the player at any given time, in any given situation when I'm using the program without having to satisfy conditions.

**Comment by Anas-Elgarhy** [comment]
This happens because I do not set a value for the reference `clip` in the `WAVPlayer` except when I play a clip, and when I close the program I call the close function from it and this is an error because at the start of the program it is with `null`

**Comment by Anas-Elgarhy** [comment]
This error also occurs with the `next`, previous`, `pause` and `stop` functions
